### ISSUE TITLE
No hay acceso a la web

### ISSUE THREAD

**Issue by genaro-villegas-alegra** [vivirenremoto/free-public-api#2]
Cuando acceso a https://free-public-api.herokuapp.com/ me dice:

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

Podemos reviasarlo

**Comment by vivirenremoto** [comment]
hola Genaro, eso ocurre cuando me quedo sin creditos en heroku ya que ahora tiro de plan gratis, recomiendo hacer fork del repo si alguien lo quiere para algo más serio https://free-public-api.herokuapp.com/

**Comment by genaro-villegas-alegra** [comment]
Gracias!

Si lo subi a mi server y lo estoy usando desde allá.

Gracias por esta herramienta.

Saludos Cordiales,

*Genaro Villegas *
SEO Analyst

***@***.***  ***@***.***>
www.alegra.com
