### ISSUE TITLE
The website is empty?

### ISSUE THREAD

**Issue by zippytyro** [vivirenremoto/free-public-api#3]
Saw the main HTML file just says loading? Are the API not available right now?

**Comment by vivirenremoto** [comment]
sorry it seems google changed some api to show a spreadsheet as a json and my website fails, i will try to fix it soon as posible

**Comment by zippytyro** [comment]
@vivirenremoto No problem man, does the site use Google sheets as a database?

**Comment by vivirenremoto** [comment]
yes, i'm using a google sheet as database, here we go fixed !
https://free-public-api.herokuapp.com/

**Comment by zippytyro** [comment]
@vivirenremoto thanks man I appreciate
